package com.example.physicsfinal

class Transliterator () {
    fun transliterateRUtoEN(word : String): String {
        val newArray = ArrayList<String>()
        for (i in word) {
            when (i.toString().toLowerCase()){
                "а" -> newArray.add("aaaaaaaaaa")
                "б" -> newArray.add("bbbbbbbbbb")
                "в" -> newArray.add("cccccccccc")
                "г" -> newArray.add("dddddddddd")
                "д" -> newArray.add("eeeeeeeeee")
                "е" -> newArray.add("ffffffffff")
                "ё" -> newArray.add("gggggggggg")
                "ж" -> newArray.add("hhhhhhhhhh")
                "з" -> newArray.add("iiiiiiiii")
                "и" -> newArray.add("jjjjjjjjjj")
                "й" -> newArray.add("a")
                "к" -> newArray.add("b")
                "л" -> newArray.add("c")
                "м" -> newArray.add("d")
                "н" -> newArray.add("e")
                "о" -> newArray.add("f")
                "п" -> newArray.add("g")
                "р" -> newArray.add("h")
                "с" -> newArray.add("i")
                "т" -> newArray.add("j")
                "у" -> newArray.add("k")
                "ф" -> newArray.add("l")
                "х" -> newArray.add("m")
                "ц" -> newArray.add("n")
                "ч" -> newArray.add("o")
                "ш" -> newArray.add("p")
                "щ" -> newArray.add("q")
                "ъ" -> newArray.add("r")
                "ы" -> newArray.add("s")
                "ь" -> newArray.add("t")
                "э" -> newArray.add("u")
                "ю" -> newArray.add("v")
                "я" -> newArray.add("w")
                "." -> newArray.add("kkkkkkkkk")
                "/" -> newArray.add("llllllllll")
                "," -> newArray.add("mmmmmmmmmm")
                ";" -> newArray.add("nnnnnnnnnn")
                "[" -> newArray.add("ooooooooo")
                "]" -> newArray.add("pppppppppp")
                "|" -> newArray.add("qqqqqqqqqq")
                ":" -> newArray.add("ssssssssss")
                "0" -> newArray.add("0")
                "1" -> newArray.add("1")
                "2" -> newArray.add("2")
                "3" -> newArray.add("3")
                "4" -> newArray.add("4")
                "5" -> newArray.add("5")
                "6" -> newArray.add("6")
                "7" -> newArray.add("7")
                "8" -> newArray.add("8")
                "9" -> newArray.add("9")
                " " -> newArray.add("_")
                "-" -> newArray.add("ttttttttttt")
            }
        }
        return newArray.joinToString(separator = "")
    }
}